name: GCP Resource creation
on:
  push:
    branches: ["main"]

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: 'Authenticate to GCP'
        uses: 'google-github-actions/auth@v0.3.1'
        with:
          create_credentials_file: 'true'
          workload_identity_provider: 'projects/605543589292/locations/global/workloadIdentityPools/github-actions-pool/providers/github'
          service_account: 'sa-github-actions@vivid-ocean-386206.iam.gserviceaccount.com'
    
      - name: 'terraform init'
        run: |-
          terraform init
          
      - name: 'terraform plan'
        run: |-
          terraform plan -input=false
      - name: 'terraform apply'
        run: |-
          terraform apply -auto-approve -input=false
